version: ~> 1.0
language: minimal
services:
  - docker

before_install:
  - docker build -t shan1500/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shan1500/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-050752626387"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  
    
