sudo: required
language: generic

services:
  - docker

before_install:
  # Build Docker image using your development Dockerfile
  - docker build -t shan1500/docker-react -f Dockerfile.dev .

script:
  # Run tests in CI mode and output coverage report
  - docker run -e CI=true shan1500/docker-react npm run test -- --coverage