name: CI/CD to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-app -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true my-app npm run test -- --coverage --watchAll=false

      - name: Zip app for deployment
        run: zip -r app.zip .

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ca-central-1
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-ca-central-1-050752626387/docker/app.zip
          VERSION_LABEL="v-${{ github.run_id }}"
          aws elasticbeanstalk create-application-version \
            --application-name docker \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=elasticbeanstalk-ca-central-1-050752626387,S3Key=docker/app.zip
          aws elasticbeanstalk update-environment \
            --environment-name Docker-env \
            --version-label $VERSION_LABEL